package:
  name: fleras
  version: 0.1.0

source:
  path: ..

requirements:
  host:
    - python
  run:
    - python
    - tensorflow
    - attrdict
    - numpy


about:
  home: https://github.com/isarandi/fleras
  license: GPL-3.0+
  license_family: GPL
  license_file: LICENSE
  summary: 'Fleras makes using Keras more flexible!'
  description: |
    Fleras provides a ModelTrainer class to help you define more complicated 
    forward passes, losses and metrics that need access to more things than 
    Keras allows. There are also a bunch of other extensions for Keras and 
    TensorFlow here.
  dev_url: https://github.com/isarandi/fleras
  doc_url: https://github.com/isarandi/fleras
  doc_source_url: https://github.com/isarandi/fleras/blob/master/README.md
